spring:
  application:
    name: Gym Progress Tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/gymtracker
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  private:
    key: classpath:app-pkcs8.key
  public:
    key: classpath:app-public.key
