spring:
  application:
    name: Gym Progress Tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/gymtracker
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,httptrace,loggers
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

jwt:
  private:
    key: classpath:app-pkcs8.key
  public:
    key: classpath:app-public.key
