spring:
  application:
    name: Gym Progress Tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_progress_tracker
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
