name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

x-setup-steps: &setup-steps
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Set up JDK 21
    uses: actions/setup-java@v3
    with:
      distribution: temurin
      java-version: '21'

  - name: Cache Maven local repository
    uses: actions/cache@v3
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - <<: *setup-steps
      - name: Build with Maven
        run: mvn -B clean verify

      - name: Run tests
        run: mvn test

  sonar:
    name: SonarQube Analysis
    needs: build
    runs-on: ubuntu-latest
    steps:
      - <<: *setup-steps
      - name: Cache SonarQube scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube Scanner
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
